"""Agrega payment_due a StudentCourse

Revision ID: 72f1ae205687
Revises: b07d903696b2
Create Date: 2025-07-31 12:40:11.124631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72f1ae205687'
down_revision = 'b07d903696b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_due', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_courses', schema=None) as batch_op:
        batch_op.drop_column('payment_due')

    # ### end Alembic commands ###
